<?php

namespace Subbotin\BackendBundle\Repository;

/**
 * CurrencyStatisticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyStatisticaRepository extends \Doctrine\ORM\EntityRepository
{
}
